// GENERATED BY localize_super_tree_examples_v2.py.
//
// Example-only localization. Package-owned strings continue to use
// SuperTreeLocalization from super_tree_field.

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

/// English/Arabic localization for the runnable example application.
class ExampleLocalization {
  /// Creates localization for [locale].
  const ExampleLocalization(this.locale);

  /// Active example locale.
  final Locale locale;

  /// Delegate used by the example [WidgetsApp]/[MaterialApp].
  static const LocalizationsDelegate<ExampleLocalization> delegate =
      _ExampleLocalizationDelegate();

  /// Locales supported by the example application.
  static const List<Locale> supportedLocales = <Locale>[
    Locale('en'),
    Locale('ar'),
  ];

  /// Returns the active localization from [context].
  static ExampleLocalization of(BuildContext context) {
    final value = Localizations.of<ExampleLocalization>(
      context,
      ExampleLocalization,
    );
    assert(value != null, 'ExampleLocalization delegate is not registered.');
    return value ?? const ExampleLocalization(Locale('en'));
  }

  /// Whether the active example language is Arabic.
  bool get isArabic => locale.languageCode == 'ar';

  /// Localized value for `appTitle`.
  String get appTitle => _value('appTitle');

  /// Localized value for `galleryEyebrow`.
  String get galleryEyebrow => _value('galleryEyebrow');

  /// Localized value for `galleryTitle`.
  String get galleryTitle => _value('galleryTitle');

  /// Localized value for `lightTheme`.
  String get lightTheme => _value('lightTheme');

  /// Localized value for `darkTheme`.
  String get darkTheme => _value('darkTheme');

  /// Localized value for `switchToArabic`.
  String get switchToArabic => _value('switchToArabic');

  /// Localized value for `switchToEnglish`.
  String get switchToEnglish => _value('switchToEnglish');

  /// Localized value for `accountTreeDemoTitle`.
  String get accountTreeDemoTitle => _value('accountTreeDemoTitle');

  /// Localized value for `accountTreeDemoSubtitle`.
  String get accountTreeDemoSubtitle => _value('accountTreeDemoSubtitle');

  /// Localized value for `fileExplorerTitle`.
  String get fileExplorerTitle => _value('fileExplorerTitle');

  /// Localized value for `fileExplorerDemoSubtitle`.
  String get fileExplorerDemoSubtitle => _value('fileExplorerDemoSubtitle');

  /// Localized value for `orgChartTitle`.
  String get orgChartTitle => _value('orgChartTitle');

  /// Localized value for `orgChartDemoSubtitle`.
  String get orgChartDemoSubtitle => _value('orgChartDemoSubtitle');

  /// Localized value for `permissionSettingsTitle`.
  String get permissionSettingsTitle => _value('permissionSettingsTitle');

  /// Localized value for `permissionSettingsDemoSubtitle`.
  String get permissionSettingsDemoSubtitle =>
      _value('permissionSettingsDemoSubtitle');

  /// Localized value for `productTreeTitle`.
  String get productTreeTitle => _value('productTreeTitle');

  /// Localized value for `productTreeDemoSubtitle`.
  String get productTreeDemoSubtitle => _value('productTreeDemoSubtitle');

  /// Localized value for `scrollConfigurationTitle`.
  String get scrollConfigurationTitle => _value('scrollConfigurationTitle');

  /// Localized value for `scrollConfigurationDemoSubtitle`.
  String get scrollConfigurationDemoSubtitle =>
      _value('scrollConfigurationDemoSubtitle');

  /// Localized value for `contextMenuDemoTitle`.
  String get contextMenuDemoTitle => _value('contextMenuDemoTitle');

  /// Localized value for `contextMenuDemoSubtitle`.
  String get contextMenuDemoSubtitle => _value('contextMenuDemoSubtitle');

  /// Localized value for `accountingEyebrow`.
  String get accountingEyebrow => _value('accountingEyebrow');

  /// Localized value for `accountTreeHeading`.
  String get accountTreeHeading => _value('accountTreeHeading');

  /// Localized value for `searchAccounts`.
  String get searchAccounts => _value('searchAccounts');

  /// Localized value for `accountHierarchy`.
  String get accountHierarchy => _value('accountHierarchy');

  /// Localized value for `accountHierarchyDescription`.
  String get accountHierarchyDescription =>
      _value('accountHierarchyDescription');

  /// Localized value for `accountColumn`.
  String get accountColumn => _value('accountColumn');

  /// Localized value for `natureBalanceSar`.
  String get natureBalanceSar => _value('natureBalanceSar');

  /// Localized value for `openedLedger`.
  String get openedLedger => _value('openedLedger');

  /// Localized value for `editTreeHint`.
  String get editTreeHint => _value('editTreeHint');

  /// Localized value for `totalAssets`.
  String get totalAssets => _value('totalAssets');

  /// Localized value for `totalLiabilities`.
  String get totalLiabilities => _value('totalLiabilities');

  /// Localized value for `totalEquity`.
  String get totalEquity => _value('totalEquity');

  /// Localized value for `netIncome`.
  String get netIncome => _value('netIncome');

  /// Localized value for `sarDebitBalance`.
  String get sarDebitBalance => _value('sarDebitBalance');

  /// Localized value for `sarCreditBalance`.
  String get sarCreditBalance => _value('sarCreditBalance');

  /// Localized value for `all`.
  String get all => _value('all');

  /// Localized value for `balanced`.
  String get balanced => _value('balanced');

  /// Localized value for `outOfBalance`.
  String get outOfBalance => _value('outOfBalance');

  /// Localized value for `searchFiles`.
  String get searchFiles => _value('searchFiles');

  /// Localized value for `projectFiles`.
  String get projectFiles => _value('projectFiles');

  /// Localized value for `projectFilesDescription`.
  String get projectFilesDescription => _value('projectFilesDescription');

  /// Localized value for `name`.
  String get name => _value('name');

  /// Localized value for `sizeModified`.
  String get sizeModified => _value('sizeModified');

  /// Localized value for `searchPeople`.
  String get searchPeople => _value('searchPeople');

  /// Localized value for `orgChart`.
  String get orgChart => _value('orgChart');

  /// Localized value for `orgChartDescription`.
  String get orgChartDescription => _value('orgChartDescription');

  /// Localized value for `roleDept`.
  String get roleDept => _value('roleDept');

  /// Localized value for `administrationPermissionsEyebrow`.
  String get administrationPermissionsEyebrow =>
      _value('administrationPermissionsEyebrow');

  /// Localized value for `permissionSettingsHeading`.
  String get permissionSettingsHeading => _value('permissionSettingsHeading');

  /// Localized value for `searchPermissions`.
  String get searchPermissions => _value('searchPermissions');

  /// Localized value for `roleSeniorAccountant`.
  String get roleSeniorAccountant => _value('roleSeniorAccountant');

  /// Localized value for `permissionsMultiDescription`.
  String get permissionsMultiDescription =>
      _value('permissionsMultiDescription');

  /// Localized value for `permissionsSingleDescription`.
  String get permissionsSingleDescription =>
      _value('permissionsSingleDescription');

  /// Localized value for `permissionColumn`.
  String get permissionColumn => _value('permissionColumn');

  /// Localized value for `scope`.
  String get scope => _value('scope');

  /// Localized value for `selectionMode`.
  String get selectionMode => _value('selectionMode');

  /// Localized value for `multi`.
  String get multi => _value('multi');

  /// Localized value for `single`.
  String get single => _value('single');

  /// Localized value for `searchProducts`.
  String get searchProducts => _value('searchProducts');

  /// Localized value for `products`.
  String get products => _value('products');

  /// Localized value for `productsDescription`.
  String get productsDescription => _value('productsDescription');

  /// Localized value for `product`.
  String get product => _value('product');

  /// Localized value for `priceStock`.
  String get priceStock => _value('priceStock');

  /// Localized value for `jumpToStart`.
  String get jumpToStart => _value('jumpToStart');

  /// Localized value for `jumpToEnd`.
  String get jumpToEnd => _value('jumpToEnd');

  /// Localized value for `reverse`.
  String get reverse => _value('reverse');

  /// Localized value for `searchScrollableItems`.
  String get searchScrollableItems => _value('searchScrollableItems');

  /// Localized value for `boundedScrollingTree`.
  String get boundedScrollingTree => _value('boundedScrollingTree');

  /// Localized value for `boundedScrollingDescription`.
  String get boundedScrollingDescription =>
      _value('boundedScrollingDescription');

  /// Localized value for `item`.
  String get item => _value('item');

  /// Localized value for `index`.
  String get index => _value('index');

  /// Localized value for `standaloneMenu`.
  String get standaloneMenu => _value('standaloneMenu');

  /// Localized value for `defaultReadOnlyMenu`.
  String get defaultReadOnlyMenu => _value('defaultReadOnlyMenu');

  /// Localized value for `defaultEditableMenu`.
  String get defaultEditableMenu => _value('defaultEditableMenu');

  /// Localized value for `replaceItems`.
  String get replaceItems => _value('replaceItems');

  /// Localized value for `extendDefaults`.
  String get extendDefaults => _value('extendDefaults');

  /// Localized value for `filterDefaults`.
  String get filterDefaults => _value('filterDefaults');

  /// Localized value for `nestedMenus`.
  String get nestedMenus => _value('nestedMenus');

  /// Localized value for `flexibleMenuPerNode`.
  String get flexibleMenuPerNode => _value('flexibleMenuPerNode');

  /// Localized value for `styleCustomization`.
  String get styleCustomization => _value('styleCustomization');

  /// Localized value for `disableContextMenus`.
  String get disableContextMenus => _value('disableContextMenus');

  /// Localizes an English source label used by static gallery metadata.
  ///
  /// Unknown strings are returned unchanged, which keeps future demo cards
  /// source-compatible until a translation is added.
  String translateSource(String source) {
    final key = _sourceKeys[source];
    return key == null ? source : _value(key);
  }

  /// Localizes the net-income supporting line.
  String netIncomeSubtitle(String income, String expense) => isArabic
      ? 'الإيرادات $income − المصروفات $expense ر.س'
      : 'Income $income − Expense $expense SAR';

  /// Localizes a displayed scroll offset.
  String scrollOffset(String value) =>
      isArabic ? 'الإزاحة $value بكسل' : 'offset $value px';

  String _value(String key) {
    final language = isArabic ? _ar : _en;
    return language[key] ?? _en[key] ?? key;
  }

  static const Map<String, String> _sourceKeys = <String, String>{
    "Account Tree": "accountTreeDemoTitle",
    "Chart of accounts · KPIs · A = L + E · DR/CR · roll-up balances":
        "accountTreeDemoSubtitle",
    "File Explorer": "fileExplorerTitle",
    "SuperTree<FileMeta> · folders + files · size / modified":
        "fileExplorerDemoSubtitle",
    "Org Chart": "orgChartTitle",
    "SuperTree<Person> · headcount roll-up · role + dept":
        "orgChartDemoSubtitle",
    "Permission Settings": "permissionSettingsTitle",
    "SuperTree<Permission> · single + multi checkbox selection":
        "permissionSettingsDemoSubtitle",
    "Product Tree": "productTreeTitle",
    "SuperTree<ProductData> · categories · SKU · price · stock":
        "productTreeDemoSubtitle",
    "Scroll Configuration": "scrollConfigurationTitle",
    "ScrollController · physics · restoration · bounded viewport":
        "scrollConfigurationDemoSubtitle",
    "Tree Context Menus": "contextMenuDemoTitle",
    "Reusable · nested · per-node context-menu customization":
        "contextMenuDemoSubtitle",
  };

  static const Map<String, String> _en = <String, String>{
    "appTitle": "Super Tree",
    "galleryEyebrow": "SUPER TREE • GALLERY",
    "galleryTitle": "Component Demos",
    "lightTheme": "Light Theme",
    "darkTheme": "Dark Theme",
    "switchToArabic": "العربية",
    "switchToEnglish": "English",
    "accountTreeDemoTitle": "Account Tree",
    "accountTreeDemoSubtitle":
        "Chart of accounts · KPIs · A = L + E · DR/CR · roll-up balances",
    "fileExplorerTitle": "File Explorer",
    "fileExplorerDemoSubtitle":
        "SuperTree<FileMeta> · folders + files · size / modified",
    "orgChartTitle": "Org Chart",
    "orgChartDemoSubtitle":
        "SuperTree<Person> · headcount roll-up · role + dept",
    "permissionSettingsTitle": "Permission Settings",
    "permissionSettingsDemoSubtitle":
        "SuperTree<Permission> · single + multi checkbox selection",
    "productTreeTitle": "Product Tree",
    "productTreeDemoSubtitle":
        "SuperTree<ProductData> · categories · SKU · price · stock",
    "scrollConfigurationTitle": "Scroll Configuration",
    "scrollConfigurationDemoSubtitle":
        "ScrollController · physics · restoration · bounded viewport",
    "contextMenuDemoTitle": "Tree Context Menus",
    "contextMenuDemoSubtitle":
        "Reusable · nested · per-node context-menu customization",
    "accountingEyebrow": "ACCOUNTING • CHART OF ACCOUNTS",
    "accountTreeHeading": "Account Tree",
    "searchAccounts": "Search by code, English or Arabic name…   ( / )",
    "accountHierarchy": "Chart of Accounts Hierarchy",
    "accountHierarchyDescription":
        "5 levels · click or use ↑↓ ← → · Enter opens a leaf · right-click to edit",
    "accountColumn": "Account",
    "natureBalanceSar": "Nature · Balance (SAR)",
    "openedLedger": "Opened ledger for account",
    "editTreeHint":
        "Drag the handle to move · right-click (or ⋮) to rename, add or delete · type filter is paused while editing",
    "totalAssets": "Total Assets",
    "totalLiabilities": "Total Liabilities",
    "totalEquity": "Total Equity",
    "netIncome": "Net Income",
    "sarDebitBalance": "SAR · debit balance",
    "sarCreditBalance": "SAR · credit balance",
    "all": "All",
    "balanced": "Balanced · A = L + E",
    "outOfBalance": "Out of balance",
    "searchFiles": "Search files…   ( / )",
    "projectFiles": "Project files",
    "projectFilesDescription":
        "TreeNode<FileMeta> · folders roll up a child count, files show size + modified",
    "name": "Name",
    "sizeModified": "Size · Modified",
    "searchPeople": "Search people…   ( / )",
    "orgChart": "Org chart",
    "orgChartDescription":
        "TreeNode<Person> · managers roll up a headcount, everyone shows role + dept",
    "roleDept": "Role · Dept",
    "administrationPermissionsEyebrow": "ADMINISTRATION • ROLES & PERMISSIONS",
    "permissionSettingsHeading": "Permission Settings",
    "searchPermissions": "Search permissions…   ( / )",
    "roleSeniorAccountant": "Role: Senior Accountant",
    "permissionsMultiDescription":
        "Check the permissions granted to this role · a module checks all its actions",
    "permissionsSingleDescription":
        "Single selection · one default action only (radio-like)",
    "permissionColumn": "Permission",
    "scope": "Scope",
    "selectionMode": "SELECTION MODE",
    "multi": "Multi",
    "single": "Single",
    "searchProducts": "Search products, SKU, or Arabic name…   ( / )",
    "products": "Products",
    "productsDescription":
        "Categories · bilingual names · SKU · unit · price · stock",
    "product": "Product",
    "priceStock": "Price · Stock",
    "jumpToStart": "Jump to start",
    "jumpToEnd": "Jump to end",
    "reverse": "Reverse",
    "searchScrollableItems": "Search scrollable items…   ( / )",
    "boundedScrollingTree": "Bounded scrolling tree",
    "boundedScrollingDescription":
        "controller owns hierarchy state · scrollController owns scroll position",
    "item": "Item",
    "index": "Index",
    "standaloneMenu": "Standalone menu",
    "defaultReadOnlyMenu": "Default read-only menu",
    "defaultEditableMenu": "Default editable menu",
    "replaceItems": "Replace items",
    "extendDefaults": "Extend defaults",
    "filterDefaults": "Filter defaults",
    "nestedMenus": "Nested menus",
    "flexibleMenuPerNode": "Flexible menu per node",
    "styleCustomization": "Style customization",
    "disableContextMenus": "Disable tree context menus",
  };

  static const Map<String, String> _ar = <String, String>{
    "appTitle": "الشجرة المتقدمة",
    "galleryEyebrow": "SUPER TREE • معرض الأمثلة",
    "galleryTitle": "عروض المكونات",
    "lightTheme": "المظهر الفاتح",
    "darkTheme": "المظهر الداكن",
    "switchToArabic": "العربية",
    "switchToEnglish": "English",
    "accountTreeDemoTitle": "شجرة الحسابات",
    "accountTreeDemoSubtitle":
        "دليل الحسابات · مؤشرات مالية · المعادلة المحاسبية · أرصدة مدينة ودائنة",
    "fileExplorerTitle": "مستكشف الملفات",
    "fileExplorerDemoSubtitle": "شجرة ملفات ومجلدات مع الحجم وتاريخ التعديل",
    "orgChartTitle": "الهيكل التنظيمي",
    "orgChartDemoSubtitle": "شجرة الموظفين · إجمالي عدد الأفراد · الدور والقسم",
    "permissionSettingsTitle": "إعدادات الصلاحيات",
    "permissionSettingsDemoSubtitle": "شجرة الصلاحيات · تحديد فردي ومتعدد",
    "productTreeTitle": "شجرة المنتجات",
    "productTreeDemoSubtitle": "فئات المنتجات · SKU · السعر · المخزون",
    "scrollConfigurationTitle": "إعدادات التمرير",
    "scrollConfigurationDemoSubtitle":
        "ScrollController · إعدادات التمرير · نافذة عرض محددة",
    "contextMenuDemoTitle": "قوائم عقد الشجرة",
    "contextMenuDemoSubtitle":
        "قوائم قابلة لإعادة الاستخدام · متداخلة · مخصصة لكل عقدة",
    "accountingEyebrow": "المحاسبة • دليل الحسابات",
    "accountTreeHeading": "شجرة الحسابات",
    "searchAccounts": "ابحث بالكود أو الاسم العربي أو الإنجليزي…   ( / )",
    "accountHierarchy": "التسلسل الهرمي لدليل الحسابات",
    "accountHierarchyDescription":
        "5 مستويات · انقر أو استخدم الأسهم · Enter لفتح الحساب · انقر بزر الفأرة الأيمن للتعديل",
    "accountColumn": "الحساب",
    "natureBalanceSar": "الطبيعة · الرصيد (ر.س)",
    "openedLedger": "تم فتح دفتر الحساب",
    "editTreeHint":
        "اسحب المقبض للنقل · انقر بزر الفأرة الأيمن (أو ⋮) لإعادة التسمية أو الإضافة أو الحذف · يتوقف فلتر النوع أثناء التعديل",
    "totalAssets": "إجمالي الأصول",
    "totalLiabilities": "إجمالي الخصوم",
    "totalEquity": "إجمالي حقوق الملكية",
    "netIncome": "صافي الدخل",
    "sarDebitBalance": "ر.س · رصيد مدين",
    "sarCreditBalance": "ر.س · رصيد دائن",
    "all": "الكل",
    "balanced": "متوازن · الأصول = الخصوم + حقوق الملكية",
    "outOfBalance": "غير متوازن",
    "searchFiles": "ابحث في الملفات…   ( / )",
    "projectFiles": "ملفات المشروع",
    "projectFilesDescription":
        "المجلدات تعرض عدد العناصر والملفات تعرض الحجم وتاريخ التعديل",
    "name": "الاسم",
    "sizeModified": "الحجم · آخر تعديل",
    "searchPeople": "ابحث عن الأشخاص…   ( / )",
    "orgChart": "الهيكل التنظيمي",
    "orgChartDescription":
        "المديرون يعرضون إجمالي عدد المرؤوسين ويظهر الدور والقسم لكل شخص",
    "roleDept": "الدور · القسم",
    "administrationPermissionsEyebrow": "الإدارة • الأدوار والصلاحيات",
    "permissionSettingsHeading": "إعدادات الصلاحيات",
    "searchPermissions": "ابحث في الصلاحيات…   ( / )",
    "roleSeniorAccountant": "الدور: محاسب أول",
    "permissionsMultiDescription":
        "حدد الصلاحيات الممنوحة لهذا الدور · تحديد الوحدة يشمل جميع إجراءاتها",
    "permissionsSingleDescription": "تحديد فردي · إجراء افتراضي واحد فقط",
    "permissionColumn": "الصلاحية",
    "scope": "النطاق",
    "selectionMode": "نمط التحديد",
    "multi": "متعدد",
    "single": "فردي",
    "searchProducts": "ابحث في المنتجات أو SKU أو الاسم العربي…   ( / )",
    "products": "المنتجات",
    "productsDescription":
        "فئات · أسماء ثنائية اللغة · SKU · الوحدة · السعر · المخزون",
    "product": "المنتج",
    "priceStock": "السعر · المخزون",
    "jumpToStart": "انتقل إلى البداية",
    "jumpToEnd": "انتقل إلى النهاية",
    "reverse": "عكس الاتجاه",
    "searchScrollableItems": "ابحث في عناصر القائمة…   ( / )",
    "boundedScrollingTree": "شجرة بتمرير محدد",
    "boundedScrollingDescription":
        "المتحكم بالشجرة يدير العقد وScrollController يدير موضع التمرير",
    "item": "العنصر",
    "index": "الرقم",
    "standaloneMenu": "قائمة مستقلة",
    "defaultReadOnlyMenu": "القائمة الافتراضية للقراءة فقط",
    "defaultEditableMenu": "القائمة الافتراضية القابلة للتعديل",
    "replaceItems": "استبدال العناصر",
    "extendDefaults": "توسيع العناصر الافتراضية",
    "filterDefaults": "تصفية العناصر الافتراضية",
    "nestedMenus": "قوائم متداخلة",
    "flexibleMenuPerNode": "قائمة مرنة لكل عقدة",
    "styleCustomization": "تخصيص المظهر",
    "disableContextMenus": "تعطيل قوائم العقد",
  };
}

/// Convenient example-localization access from [BuildContext].
extension ExampleLocalizationBuildContext on BuildContext {
  /// Returns the active example localization.
  ExampleLocalization get exampleLocalization => ExampleLocalization.of(this);
}

class _ExampleLocalizationDelegate
    extends LocalizationsDelegate<ExampleLocalization> {
  const _ExampleLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => ExampleLocalization.supportedLocales.any(
    (item) => item.languageCode == locale.languageCode,
  );

  @override
  Future<ExampleLocalization> load(Locale locale) =>
      SynchronousFuture<ExampleLocalization>(ExampleLocalization(locale));

  @override
  bool shouldReload(_ExampleLocalizationDelegate old) => false;
}
