flutter_intl:
  enabled: true
  
arb-dir: lib/localization
template-arb-file: intl_en.arb
output-localization-file: l10n.dart
output-class: SuperTreeLocalization
output-dir: lib/localization/generated
nullable-getter: false
use-escaping: true
use_deferred_loading: true
